//
// Created by Jason Torrence on 3/30/2019.
//

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "../Params/Params.h"
#include "../MT/mt19937ar.h"
#include "MatrGen.h"
#include "../Utils/Utils.h"



/**
 * genMatrix: creates a double pointer of random values within bounds for use in algorthms
 *
 * genMatrix creates an double pointer of values based on the params struct, the dimension,
 * and the bounds are decided by the algNum and values within params, though this primarily
 * calls genLine for the creation of random values.
 *
 * @param int dimension: describes how many values to generate
 * @param Struct params: describes the ranges random numbers should fall between
 * @param int algNum: describes which ranges within params the random numbers should fall between.
 * @return double* line: to fill a row in the matrix
 */
double * genRandLine(double upperBound, double lowerBound, int columns){

    //printf("attempting to allocate memory: size of double * %d.\n", dimension);
    double *column = (double *) calloc(columns, sizeof(double));

    if(!column){
        fprintf(stderr, "Column of matrix failed to allocate the necessary memory.");
        exit(-1);
    }

    double range = upperBound - lowerBound;

#pragma acc kernels
    for (int i = 0; i < columns; i++) {
        //printf("generating random number: %d.\n", i);
        double randNum = (genrand_real1() * range) + lowerBound;
        column[i] = randNum;
    }
    return column;
}

/**
 * genLine: creates a pointer of random values within bounds for use in algorthms
 *
 * genLines simply fills a vector with random values within specific bounds.
 *
 * @param int algNum: used to decide bounds in genLine
 * @param unsigned int randSeed: used to seed Mersenne Twister
 * @param struct Params params: used for bounds and values to decide the size of the vector
 * @param int dimension: used to decide the "rows" in the matrix
 * @return double** matrix: for use in algorithms
 */
double ** genMatrix(double upperBound, double lowerBound, int rows, int columns, int randSeed){

    double ** matrix = (double **) calloc(rows, sizeof(double));

    if(!matrix){
        fprintf(stderr, "'matrix', failed to allocate the necessary memory.");
        exit(-1);
    }

    //printf("Size of Dimension in MatrGen: %d.\n", dimension);
    init_genrand(randSeed);

#pragma acc kernels
    for (int i = 0; i < rows; i++) {
        //printf("Generating Line: %d.\n", i);
        matrix[i] = genRandLine(upperBound, lowerBound, columns);
    }

    return matrix;
}

/**
 * freeMatr: frees memory generated by having double pointer arrays
 *
 * simply takes in the matrix and the sample size
 *
 * @param double** matrix: to be cleared
 * @param int size: to define how many double* are in the matrix
 *
 */
void freeMatr(double** matrix, int size){
    for(int i = 0; i < size; i++){
        free(matrix[i]);
    }
    free(matrix);
}
